# Generated by Django 4.0.4 on 2022-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='hostel_name',
            field=models.CharField(default='N/A', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='user_name',
            field=models.CharField(default='N/A', max_length=25),
            preserve_default=False,
        ),
    ]
