# Generated by Django 4.0.4 on 2022-05-24 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_input_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='input',
            name='image',
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(choices=[('1', 'Tip'), ('2', 'Recommendation'), ('3', 'Review')], default='1', max_length=25),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
